# Generated by Django 5.2.8 on 2025-12-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['market'], name='disputes_di_market__2c170a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['market', 'status'], name='disputes_di_market__3e3da2_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['user'], name='disputes_di_user_id_e022b4_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['user', '-created_at'], name='disputes_di_user_id_281df5_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-created_at'], name='disputes_di_status_e85bdd_idx'),
        ),
    ]
