# Generated by Django 5.2.8 on 2025-12-15 18:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('resolution_outcome', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True)),
                ('liquidity_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
                ('onchain_market_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('onchain_tx_hash', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Market Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketKnowledgeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('price', models.DecimalField(decimal_places=6, default=0.5, max_digits=8)),
                ('supply', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_price', models.DecimalField(decimal_places=6, max_digits=8)),
                ('no_price', models.DecimalField(decimal_places=6, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_outcome', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('dispute_window', models.DateTimeField()),
                ('bond_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('onchain_tx_hash', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Knowledge Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='markets_kno_slug_dcf31e_idx'), models.Index(fields=['name'], name='markets_kno_name_aa63e9_idx')],
            },
        ),
    ]
