# Generated by Django 5.2.8 on 2025-12-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_markets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='market',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='markets.marketcategory'),
        ),
        migrations.AddField(
            model_name='marketknowledgetag',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_tags', to='markets.market'),
        ),
        migrations.AddField(
            model_name='marketknowledgetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='markets.knowledgetag'),
        ),
        migrations.AddField(
            model_name='outcometoken',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_tokens', to='markets.market'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='markets.market'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='markets.market'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='resolver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_markets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', '-created_at'], name='markets_mar_status_f5bebe_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['category', 'status'], name='markets_mar_categor_1919dc_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['ends_at'], name='markets_mar_ends_at_1291bf_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['created_by'], name='markets_mar_created_1fa567_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['onchain_market_id'], name='markets_mar_onchain_30fab0_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['onchain_tx_hash'], name='markets_mar_onchain_f8cbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='marketknowledgetag',
            index=models.Index(fields=['market', 'tag'], name='markets_mar_market__d53066_idx'),
        ),
        migrations.AddIndex(
            model_name='marketknowledgetag',
            index=models.Index(fields=['tag'], name='markets_mar_tag_id_269e86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketknowledgetag',
            unique_together={('market', 'tag')},
        ),
        migrations.AddIndex(
            model_name='outcometoken',
            index=models.Index(fields=['market', 'outcome_type'], name='markets_out_market__5ac48b_idx'),
        ),
        migrations.AddIndex(
            model_name='outcometoken',
            index=models.Index(fields=['market', '-updated_at'], name='markets_out_market__6ce887_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outcometoken',
            unique_together={('market', 'outcome_type')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['market', '-timestamp'], name='markets_pri_market__bc52ef_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['-timestamp'], name='markets_pri_timesta_3834bb_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['market'], name='markets_res_market__b4f7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['resolved_outcome'], name='markets_res_resolve_15ad5a_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['-created_at'], name='markets_res_created_05045e_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['onchain_tx_hash'], name='markets_res_onchain_fbf049_idx'),
        ),
    ]
