# Generated by Django 5.2.8 on 2025-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_create_volume_by_tag_view'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='knowledgetag',
            index=models.Index(fields=['slug'], name='markets_kno_slug_dcf31e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgetag',
            index=models.Index(fields=['name'], name='markets_kno_name_aa63e9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketknowledgetag',
            index=models.Index(fields=['market', 'tag'], name='markets_mar_market__d53066_idx'),
        ),
        migrations.AddIndex(
            model_name='marketknowledgetag',
            index=models.Index(fields=['tag'], name='markets_mar_tag_id_269e86_idx'),
        ),
    ]
