# Generated by Django 5.2.8 on 2025-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address used in login attempt', max_length=254)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], db_index=True, default='FAILED', max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('INVALID_CREDENTIALS', 'Invalid email or password'), ('ACCOUNT_DISABLED', 'Account is disabled'), ('ACCOUNT_LOCKED', 'Account is locked'), ('TOO_MANY_ATTEMPTS', 'Too many failed attempts'), ('SUSPICIOUS_IP', 'Suspicious IP address'), ('MISSING_CREDENTIALS', 'Missing email or password')], help_text='Reason for failure if login was unsuccessful', max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request', null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text='Country code from IP', max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, help_text='Mobile, Desktop, Tablet, etc.', max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, help_text='Operating system', max_length=100, null=True)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Risk score from 0-100', max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format')),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'db_table': 'login_attempts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('RATE_LIMIT', 'Rate Limit Exceeded'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format')),
            ],
            options={
                'db_table': 'security_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
