# Generated by Django 5.2.8 on 2025-12-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='security_lo_timesta_4c7ded_idx',
            old_name='security_lo_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='security_lo_event_t_46eca0_idx',
            old_name='security_lo_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='security_lo_ip_fbe9ce_idx',
            old_name='security_lo_ip_times_idx',
        ),
    ]
