# Generated by Django 5.2.8 on 2025-12-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_engine', '0003_loginattempt_and_securitylog_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_timesta_02f426_idx',
            old_name='login_att_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_email_d532d7_idx',
            old_name='login_att_email_t_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_ip_addr_d622c8_idx',
            old_name='login_att_ip_add_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_success_22e1ce_idx',
            old_name='login_att_success_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_status_9d09a8_idx',
            old_name='login_att_status_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_is_susp_82cea8_idx',
            old_name='login_att_is_susp_idx',
        ),
    ]
