# Generated by Django 5.2.8 on 2025-12-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user'], name='trades_trad_user_id_561ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', '-created_at'], name='trades_trad_user_id_1f28fa_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market'], name='trades_trad_market__682b95_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market', '-created_at'], name='trades_trad_market__97a43c_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['outcome_type'], name='trades_trad_outcome_906fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['outcome_type', '-created_at'], name='trades_trad_outcome_f251ee_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trade_type', '-created_at'], name='trades_trad_trade_t_e0cc67_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['onchain_tx_hash'], name='trades_trad_onchain_2699d5_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market', 'outcome_type'], name='trades_trad_market__95e5ee_idx'),
        ),
    ]
