# Generated by Django 5.2.8 on 2025-11-23 17:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Market Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('resolution_outcome', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True)),
                ('liquidity_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
                ('onchain_market_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('onchain_tx_hash', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_markets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='markets.marketcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('price', models.DecimalField(decimal_places=6, default=0.5, max_digits=8)),
                ('supply', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_tokens', to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_price', models.DecimalField(decimal_places=6, max_digits=8)),
                ('no_price', models.DecimalField(decimal_places=6, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='markets.market')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_outcome', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('dispute_window', models.DateTimeField()),
                ('bond_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('onchain_tx_hash', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='markets.market')),
                ('resolver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', '-created_at'], name='markets_mar_status_f5bebe_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['category', 'status'], name='markets_mar_categor_1919dc_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['ends_at'], name='markets_mar_ends_at_1291bf_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['created_by'], name='markets_mar_created_1fa567_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['onchain_market_id'], name='markets_mar_onchain_30fab0_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['onchain_tx_hash'], name='markets_mar_onchain_f8cbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='outcometoken',
            index=models.Index(fields=['market', 'outcome_type'], name='markets_out_market__5ac48b_idx'),
        ),
        migrations.AddIndex(
            model_name='outcometoken',
            index=models.Index(fields=['market', '-updated_at'], name='markets_out_market__6ce887_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outcometoken',
            unique_together={('market', 'outcome_type')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['market', '-timestamp'], name='markets_pri_market__bc52ef_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['-timestamp'], name='markets_pri_timesta_3834bb_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['market'], name='markets_res_market__b4f7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['resolved_outcome'], name='markets_res_resolve_15ad5a_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['-created_at'], name='markets_res_created_05045e_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['onchain_tx_hash'], name='markets_res_onchain_fbf049_idx'),
        ),
    ]
