# Generated by Django 5.2.8 on 2025-11-23 17:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('amount_staked', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tokens_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_at_execution', models.DecimalField(decimal_places=6, max_digits=8)),
                ('onchain_tx_hash', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('onchain_trade_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='trades_trad_user_id_561ccf_idx'), models.Index(fields=['user', '-created_at'], name='trades_trad_user_id_1f28fa_idx'), models.Index(fields=['market'], name='trades_trad_market__682b95_idx'), models.Index(fields=['market', '-created_at'], name='trades_trad_market__97a43c_idx'), models.Index(fields=['outcome_type'], name='trades_trad_outcome_906fc8_idx'), models.Index(fields=['outcome_type', '-created_at'], name='trades_trad_outcome_f251ee_idx'), models.Index(fields=['trade_type', '-created_at'], name='trades_trad_trade_t_e0cc67_idx'), models.Index(fields=['onchain_tx_hash'], name='trades_trad_onchain_2699d5_idx'), models.Index(fields=['market', 'outcome_type'], name='trades_trad_market__95e5ee_idx')],
            },
        ),
    ]
