# Generated by Django 5.2.8 on 2025-12-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexer', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onchaineventlog',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onchain_events', to='markets.market'),
        ),
        migrations.AddIndex(
            model_name='onchaintransaction',
            index=models.Index(fields=['tx_hash'], name='indexer_onc_tx_hash_b3b4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaintransaction',
            index=models.Index(fields=['network', 'status'], name='indexer_onc_network_e935d7_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaintransaction',
            index=models.Index(fields=['block_number'], name='indexer_onc_block_n_62aa8b_idx'),
        ),
        migrations.AddField(
            model_name='onchaineventlog',
            name='onchain_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='indexer.onchaintransaction'),
        ),
        migrations.AddIndex(
            model_name='onchaineventlog',
            index=models.Index(fields=['tx_hash'], name='indexer_onc_tx_hash_21f4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaineventlog',
            index=models.Index(fields=['market'], name='indexer_onc_market__e055a2_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaineventlog',
            index=models.Index(fields=['event_name'], name='indexer_onc_event_n_215c16_idx'),
        ),
        migrations.AddIndex(
            model_name='onchaineventlog',
            index=models.Index(fields=['user_address'], name='indexer_onc_user_ad_3f090d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onchaineventlog',
            unique_together={('tx_hash', 'log_index')},
        ),
    ]
