# Generated by Django 5.2.8 on 2025-12-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0002_initial'),
        ('trades', '0002_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmanipulationscore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manipulation_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='modelpredictionaudit',
            index=models.Index(fields=['model_name', '-created_at'], name='training_mo_model_n_dfd6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='modelpredictionaudit',
            index=models.Index(fields=['-created_at'], name='training_mo_created_a4425e_idx'),
        ),
        migrations.AddIndex(
            model_name='platformhealthmetric',
            index=models.Index(fields=['-created_at'], name='training_pl_created_9efd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='platformhealthmetric',
            index=models.Index(fields=['health_status', '-created_at'], name='training_pl_health__585cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformhealthmetric',
            index=models.Index(fields=['alert_level', '-created_at'], name='training_pl_alert_l_ba81d3_idx'),
        ),
        migrations.AddField(
            model_name='traderiskprediction',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='markets.market'),
        ),
        migrations.AddField(
            model_name='traderiskprediction',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='trades.trade'),
        ),
        migrations.AddField(
            model_name='traderiskprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='marketmanipulationscore',
            index=models.Index(fields=['market', '-created_at'], name='training_ma_market__ca4444_idx'),
        ),
        migrations.AddIndex(
            model_name='marketmanipulationscore',
            index=models.Index(fields=['user', '-created_at'], name='training_ma_user_id_5fc350_idx'),
        ),
        migrations.AddIndex(
            model_name='marketmanipulationscore',
            index=models.Index(fields=['is_manipulation_suspected', '-created_at'], name='training_ma_is_mani_506718_idx'),
        ),
        migrations.AddIndex(
            model_name='marketmanipulationscore',
            index=models.Index(fields=['risk_level', '-created_at'], name='training_ma_risk_le_fd50da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketmanipulationscore',
            unique_together={('market', 'user', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='traderiskprediction',
            index=models.Index(fields=['user', '-created_at'], name='training_tr_user_id_730cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='traderiskprediction',
            index=models.Index(fields=['trade'], name='training_tr_trade_i_25fe7f_idx'),
        ),
        migrations.AddIndex(
            model_name='traderiskprediction',
            index=models.Index(fields=['risk_level', '-created_at'], name='training_tr_risk_le_bdf51c_idx'),
        ),
        migrations.AddIndex(
            model_name='traderiskprediction',
            index=models.Index(fields=['-created_at'], name='training_tr_created_a7b1fb_idx'),
        ),
    ]
