# Generated by Django 5.2.8 on 2025-12-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketmanipulationscore',
            new_name='training_ma_market__ca4444_idx',
            old_name='ml_marketma_market__c86e17_idx',
        ),
        migrations.RenameIndex(
            model_name='marketmanipulationscore',
            new_name='training_ma_user_id_5fc350_idx',
            old_name='ml_marketma_user_id_194602_idx',
        ),
        migrations.RenameIndex(
            model_name='marketmanipulationscore',
            new_name='training_ma_is_mani_506718_idx',
            old_name='ml_marketma_is_mani_1702a8_idx',
        ),
        migrations.RenameIndex(
            model_name='marketmanipulationscore',
            new_name='training_ma_risk_le_fd50da_idx',
            old_name='ml_marketma_risk_le_9a866f_idx',
        ),
        migrations.RenameIndex(
            model_name='modelpredictionaudit',
            new_name='training_mo_model_n_dfd6c1_idx',
            old_name='ml_modelpre_model_n_594ade_idx',
        ),
        migrations.RenameIndex(
            model_name='modelpredictionaudit',
            new_name='training_mo_created_a4425e_idx',
            old_name='ml_modelpre_created_d569ce_idx',
        ),
        migrations.RenameIndex(
            model_name='platformhealthmetric',
            new_name='training_pl_created_9efd2c_idx',
            old_name='ml_platform_created_b64003_idx',
        ),
        migrations.RenameIndex(
            model_name='platformhealthmetric',
            new_name='training_pl_health__585cc2_idx',
            old_name='ml_platform_health__9be689_idx',
        ),
        migrations.RenameIndex(
            model_name='platformhealthmetric',
            new_name='training_pl_alert_l_ba81d3_idx',
            old_name='ml_platform_alert_l_926e98_idx',
        ),
        migrations.RenameIndex(
            model_name='traderiskprediction',
            new_name='training_tr_user_id_730cbf_idx',
            old_name='ml_traderis_user_id_cc5803_idx',
        ),
        migrations.RenameIndex(
            model_name='traderiskprediction',
            new_name='training_tr_trade_i_25fe7f_idx',
            old_name='ml_traderis_trade_i_5f07cd_idx',
        ),
        migrations.RenameIndex(
            model_name='traderiskprediction',
            new_name='training_tr_risk_le_bdf51c_idx',
            old_name='ml_traderis_risk_le_08f3a6_idx',
        ),
        migrations.RenameIndex(
            model_name='traderiskprediction',
            new_name='training_tr_created_a7b1fb_idx',
            old_name='ml_traderis_created_af8328_idx',
        ),
    ]
