# Generated by Django 5.2.8 on 2026-01-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TRADER', 'Trader'), ('WHALE', 'Whale'), ('BLOCKED', 'Blocked')], default='TRADER', max_length=20),
        ),
    ]
