# Generated by Django 5.2.8 on 2025-12-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user'], name='positions_p_user_id_6a01b2_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', '-updated_at'], name='positions_p_user_id_03583c_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['market'], name='positions_p_market__831664_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['market', '-updated_at'], name='positions_p_market__099fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'market'], name='positions_p_user_id_a9f43b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('user', 'market')},
        ),
    ]
