# Generated by Django 5.2.8 on 2025-11-23 17:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('onchain_tx_hash', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('onchain_liquidity_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_events', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['market'], name='liquidity_l_market__b6fe98_idx'), models.Index(fields=['market', '-created_at'], name='liquidity_l_market__67bfe9_idx'), models.Index(fields=['user'], name='liquidity_l_user_id_fc77b6_idx'), models.Index(fields=['user', '-created_at'], name='liquidity_l_user_id_629d72_idx'), models.Index(fields=['event_type', '-created_at'], name='liquidity_l_event_t_8fc747_idx'), models.Index(fields=['onchain_tx_hash'], name='liquidity_l_onchain_cbb0af_idx'), models.Index(fields=['market', 'event_type'], name='liquidity_l_market__be7ec4_idx')],
            },
        ),
    ]
