# Generated by Django 5.2.8 on 2025-12-15 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liquidity', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidityevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='liquidityevent',
            index=models.Index(fields=['market'], name='liquidity_l_market__b6fe98_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityevent',
            index=models.Index(fields=['market', '-created_at'], name='liquidity_l_market__67bfe9_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityevent',
            index=models.Index(fields=['user'], name='liquidity_l_user_id_fc77b6_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityevent',
            index=models.Index(fields=['user', '-created_at'], name='liquidity_l_user_id_629d72_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityevent',
            index=models.Index(fields=['event_type', '-created_at'], name='liquidity_l_event_t_8fc747_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityevent',
            index=models.Index(fields=['onchain_tx_hash'], name='liquidity_l_onchain_cbb0af_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityevent',
            index=models.Index(fields=['market', 'event_type'], name='liquidity_l_market__be7ec4_idx'),
        ),
    ]
