# Generated by Django 5.2.8 on 2025-11-23 17:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_tokens', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('no_tokens', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_staked', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='positions_p_user_id_6a01b2_idx'), models.Index(fields=['user', '-updated_at'], name='positions_p_user_id_03583c_idx'), models.Index(fields=['market'], name='positions_p_market__831664_idx'), models.Index(fields=['market', '-updated_at'], name='positions_p_market__099fa2_idx'), models.Index(fields=['user', 'market'], name='positions_p_user_id_a9f43b_idx')],
                'unique_together': {('user', 'market')},
            },
        ),
    ]
