# Generated by Django 5.2.8 on 2025-11-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=80, unique=True)),
                ('network', models.CharField(default='sepolia', max_length=32)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tx_hash'], name='indexer_onc_tx_hash_b3b4e4_idx'), models.Index(fields=['network', 'status'], name='indexer_onc_network_e935d7_idx'), models.Index(fields=['block_number'], name='indexer_onc_block_n_62aa8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnchainEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64)),
                ('tx_hash', models.CharField(max_length=80)),
                ('log_index', models.IntegerField()),
                ('user_address', models.CharField(blank=True, max_length=64)),
                ('payload_json', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onchain_events', to='markets.market')),
                ('onchain_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='indexer.onchaintransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['tx_hash'], name='indexer_onc_tx_hash_21f4cd_idx'), models.Index(fields=['market'], name='indexer_onc_market__e055a2_idx'), models.Index(fields=['event_name'], name='indexer_onc_event_n_215c16_idx'), models.Index(fields=['user_address'], name='indexer_onc_user_ad_3f090d_idx')],
                'unique_together': {('tx_hash', 'log_index')},
            },
        ),
    ]
